#!/bin/sh

mkdir -p /etc/customlogo
chmod 755 /etc/customlogo

if [ -f /etc/init.d/customlogo ]; then
	chmod +x /etc/init.d/customlogo
	/etc/init.d/customlogo enable >/dev/null 2>&1 || true
	/etc/init.d/customlogo start >/dev/null 2>&1 || true
fi

exit 0
