include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-customlogo
PKG_VERSION:=1.0.2
PKG_RELEASE:=1

LUCI_TITLE:=LuCI Support for Custom Web UI Logo and Favicon
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
